language: ruby
cache: bundler

before_install:
  - bundle config set deployment 'true'
  - bundle install

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
 - bundle exec rspec spec
 - bundle exec cucumber

branches:
  only:
  - master
